// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DefaultResponse struct {
	Message string `json:"message"`
}

type NewUser struct {
	UserID          string `json:"userId"`
	Username        string `json:"username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	Role            string `json:"role"`
}
